[package]
name = "inset-foundation"
description = "App, Handle, and Entity for Inset"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
async-task.workspace = true
indexmap.workspace = true
inset-embedder.workspace = true
slotmap.workspace = true

[lints]
workspace = true
