[workspace]
resolver = "3"
members = ["crates/*", "examples/*"]

[workspace.package]
edition = "2024"
version = "0.5.0"
license = "MIT"
repository = "https://github.com/inset-rs/inset"
homepage = "https://inset.rs"
keywords = ["ui", "gui", "flutter"]
categories = ["gui"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
arboard = "3"
async-task = "4"
indexmap = "2"
inset = { version = "0.5.0", path = "crates/inset" }
inset-animation = { version = "0.5.0", path = "crates/inset-animation" }
inset-cupertino = { version = "0.5.0", path = "crates/inset-cupertino" }
inset-embedder = { version = "0.5.0", path = "crates/inset-embedder" }
inset-embedder-android = { version = "0.5.0", path = "crates/inset-embedder-android" }
inset-embedder-default = { version = "0.5.0", path = "crates/inset-embedder-default" }
inset-embedder-web = { version = "0.5.0", path = "crates/inset-embedder-web" }
inset-embedder-winit = { version = "0.5.0", path = "crates/inset-embedder-winit" }
inset-foundation = { version = "0.5.0", path = "crates/inset-foundation" }
inset-gestures = { version = "0.5.0", path = "crates/inset-gestures" }
inset-macros = { version = "0.5.0", path = "crates/inset-macros" }
inset-painting = { version = "0.5.0", path = "crates/inset-painting" }
inset-physics = { version = "0.5.0", path = "crates/inset-physics" }
inset-rendering = { version = "0.5.0", path = "crates/inset-rendering" }
inset-scheduler = { version = "0.5.0", path = "crates/inset-scheduler" }
inset-services = { version = "0.5.0", path = "crates/inset-services" }
inset-shell = { version = "0.5.0", path = "crates/inset-shell" }
inset-test = { version = "0.5.0", path = "crates/inset-test" }
inset-widgets = { version = "0.5.0", path = "crates/inset-widgets" }
slotmap = "1"
unicode-general-category = "1"
unicode-segmentation = "1"
winit = "0.30"
raw-window-handle = "0.6"
valo = "0.6.0"
valo-codec = "0.6.0"
valo-system-fonts = "0.6.0"
valo-geometry = "0.6.0"
wgpu = "30"
pollster = "0.4"
web-time = "1"
