[workspace]
resolver = "3"
members = ["crates/*", "examples/*"]

[workspace.package]
edition = "2024"
license = "MIT"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
arboard = "3"
async-task = "4"
indexmap = "2"
reveal-animation = { path = "crates/reveal-animation" }
reveal-cupertino = { path = "crates/reveal-cupertino" }
reveal-embedder = { path = "crates/reveal-embedder" }
reveal-embedder-winit = { path = "crates/reveal-embedder-winit" }
reveal-foundation = { path = "crates/reveal-foundation" }
reveal-gestures = { path = "crates/reveal-gestures" }
reveal-painting = { path = "crates/reveal-painting" }
reveal-physics = { path = "crates/reveal-physics" }
reveal-rendering = { path = "crates/reveal-rendering" }
reveal-scheduler = { path = "crates/reveal-scheduler" }
reveal-services = { path = "crates/reveal-services" }
reveal-shell = { path = "crates/reveal-shell" }
reveal-widgets = { path = "crates/reveal-widgets" }
slotmap = "1"
unicode-general-category = "1"
unicode-segmentation = "1"
winit = "0.30"
valo = "0.4.3"
valo-codec = "0.4.3"
valo-system-fonts = "0.4.3"
valo-geometry = "0.4.3"
wgpu = "30"
pollster = "0.4"
