[package]
name = "reveal-embedder-winit"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["image-apple", "image-software", "image-worker"]
image-software = ["dep:valo-codec-software"]
image-apple = ["dep:valo-codec-apple"]
image-worker = ["valo-codec/worker"]

[dependencies]
arboard.workspace = true
reveal-embedder.workspace = true
valo.workspace = true
valo-codec.workspace = true
valo-codec-software = { version = "0.4.3", optional = true }
wgpu.workspace = true
pollster.workspace = true
winit.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
valo-codec-apple = { version = "0.4.3", optional = true }

[lints]
workspace = true
