[package]
name = "inset-animation"
description = "Animation controllers and curves for Inset"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
inset-foundation.workspace = true
inset-embedder.workspace = true
inset-physics.workspace = true
inset-scheduler.workspace = true

[lints]
workspace = true
