[package]
name = "inset-painting"
description = "Alignment, decoration, and text painting for Inset"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
indexmap.workspace = true
inset-embedder.workspace = true
inset-foundation.workspace = true
inset-scheduler.workspace = true

[dev-dependencies]
inset-embedder = { workspace = true, features = ["test-support"] }
valo-system-fonts.workspace = true

[lints]
workspace = true
