//! Flutter counterpart: `package:flutter/painting.dart`.
#![feature(arbitrary_self_types)]

mod alignment;
mod basic_types;
mod beveled_rectangle_border;
mod binding;
mod border_radius;
mod borders;
mod box_border;
mod box_decoration;
mod box_fit;
mod box_shadow;
mod circle_border;
mod clip;
mod colors;
mod continuous_rectangle_border;
mod debug;
mod decoration;
mod draw;
mod edge_insets;
mod fractional_offset;
mod geometry;
mod image_provider;
mod inline_span;
mod linear_border;
mod matrix_utils;
mod oval_border;
mod paint_utilities;
mod rounded_rectangle_border;
mod shape_decoration;
mod stadium_border;
mod text_painter;
mod text_scaler;
mod text_span;
mod text_style;

pub use alignment::*;
pub use basic_types::*;
pub use beveled_rectangle_border::*;
pub use binding::*;
pub use border_radius::*;
pub use borders::*;
pub use box_border::*;
pub use box_decoration::*;
pub use box_fit::*;
pub use box_shadow::*;
pub use circle_border::*;
pub use clip::*;
pub use colors::*;
pub use continuous_rectangle_border::*;
pub use debug::*;
pub use decoration::*;
pub use draw::{draw_drrect, draw_oval, draw_rrect, draw_rsuperellipse};
pub use edge_insets::*;
pub use fractional_offset::*;
pub use geometry::*;
pub use image_provider::*;
pub use inline_span::*;
pub use linear_border::*;
pub use matrix_utils::*;
pub use oval_border::*;
pub use paint_utilities::*;
pub use rounded_rectangle_border::*;
pub use shape_decoration::*;
pub use stadium_border::*;
pub use text_painter::*;
pub use text_scaler::*;
pub use text_span::*;
pub use text_style::*;
