//! Flutter counterpart: `packages/flutter/lib/src/widgets`.
//!
//! The widget framework: `framework.dart` (widgets, elements, state, the build owner).
//! The binding, `runApp`, and the widgets themselves follow.
#![feature(arbitrary_self_types)]

mod binding;
mod framework;
#[cfg(test)]
mod test_harness;
mod view;
mod widgets;

pub use binding::*;
pub use framework::*;
pub use view::*;
pub use widgets::actions::*;
pub use widgets::animated_size::*;
pub use widgets::annotated_region::*;
pub use widgets::app::*;
pub use widgets::app_lifecycle_listener::*;
pub use widgets::autofill::*;
pub use widgets::automatic_keep_alive::*;
pub use widgets::banner::*;
pub use widgets::basic::*;
pub use widgets::container::*;
pub use widgets::context_menu_button_item::*;
pub use widgets::default_text_editing_shortcuts::*;
pub use widgets::desktop_text_selection_toolbar_layout_delegate::*;
pub use widgets::drag_target::*;
pub use widgets::draggable_scrollable_sheet::*;
pub use widgets::editable_text::*;
pub use widgets::expansible::*;
pub use widgets::feedback::*;
pub use widgets::focus_manager::*;
pub use widgets::focus_scope::*;
pub use widgets::focus_traversal::*;
pub use widgets::gesture_detector::*;
pub use widgets::heroes::*;
pub use widgets::icon::*;
pub use widgets::icon_data::*;
pub use widgets::icon_theme::*;
pub use widgets::icon_theme_data::*;
pub use widgets::image::*;
pub use widgets::implicit_animations::*;
pub use widgets::inherited_notifier::*;
pub use widgets::layout_builder::*;
pub use widgets::localizations::*;
pub use widgets::magnifier::*;
pub use widgets::media_query::*;
pub use widgets::modal_barrier::*;
pub use widgets::navigation_toolbar::*;
pub use widgets::navigator::*;
pub use widgets::navigator_pop_handler::*;
pub use widgets::notification_listener::*;
pub use widgets::overlay::*;
pub use widgets::page_storage::*;
pub use widgets::pages::*;
pub use widgets::pop_scope::*;
pub use widgets::preferred_size::*;
pub use widgets::primary_scroll_controller::*;
pub use widgets::radio_group::*;
pub use widgets::restoration::*;
pub use widgets::restoration_properties::*;
pub use widgets::routes::*;
pub use widgets::safe_area::*;
pub use widgets::scroll_activity::*;
pub use widgets::scroll_configuration::*;
pub use widgets::scroll_context::*;
pub use widgets::scroll_controller::*;
pub use widgets::scroll_delegate::*;
pub use widgets::scroll_metrics::*;
pub use widgets::scroll_notification::*;
pub use widgets::scroll_notification_observer::*;
pub use widgets::scroll_physics::*;
pub use widgets::scroll_position::*;
pub use widgets::scroll_position_with_single_context::*;
pub use widgets::scroll_simulation::*;
pub use widgets::scroll_view::*;
pub use widgets::scrollable::*;
pub use widgets::scrollable_helpers::*;
pub use widgets::scrollbar::*;
pub use widgets::shared_app_data::*;
pub use widgets::shortcuts::*;
pub use widgets::single_child_scroll_view::*;
pub use widgets::sliver::*;
pub use widgets::sliver_persistent_header::*;
pub use widgets::spell_check::*;
pub use widgets::standard_component_type::*;
pub use widgets::status_transitions::*;
pub use widgets::system_context_menu::*;
pub use widgets::tap_region::*;
pub use widgets::text::*;
pub use widgets::text_editing_intents::*;
pub use widgets::text_selection::*;
pub use widgets::text_selection_toolbar_anchors::*;
pub use widgets::text_selection_toolbar_layout_delegate::*;
pub use widgets::ticker_provider::*;
pub use widgets::title::*;
pub use widgets::transitions::*;
pub use widgets::undo_history::*;
pub use widgets::value_listenable_builder::*;
pub use widgets::viewport::*;
pub use widgets::visibility::*;
pub use widgets::widget_state::*;
