[package]
name = "inset-test"
description = "Test scaffolding for Inset: a platform and a view to run an App under"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
inset-embedder.workspace = true

[lints]
workspace = true
