[package]
name = "inset-cupertino"
description = "iOS-style Cupertino widgets for Inset"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
indexmap.workspace = true
inset-animation.workspace = true
inset-embedder.workspace = true
inset-foundation.workspace = true
inset-gestures.workspace = true
inset-painting.workspace = true
inset-physics.workspace = true
inset-rendering.workspace = true
inset-scheduler.workspace = true
inset-services.workspace = true
inset-widgets.workspace = true

[dev-dependencies]
inset-test.workspace = true
valo-system-fonts.workspace = true

[lints]
workspace = true
