[package]
name = "inset-rendering"
description = "Render-object tree and layout for Inset"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
indexmap.workspace = true
inset-animation.workspace = true
inset-embedder.workspace = true
inset-foundation.workspace = true
inset-gestures.workspace = true
inset-painting.workspace = true
inset-scheduler.workspace = true
inset-services.workspace = true
unicode-general-category.workspace = true

[dev-dependencies]
inset-test.workspace = true
inset-embedder = { workspace = true, features = ["test-support"] }
valo.workspace = true
valo-system-fonts.workspace = true

[lints]
workspace = true
